### ISSUE TITLE
Не могу инициализировать User'а

### ISSUE THREAD

**Issue by Hunternif** [andreymal/tabun_api#1]
Строчка `tabun_api.User()` - с параметрами или без - выдает ошибку:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tabun_api\__init__.py", line 424, in __init__
    cook.load(resp.headers.get("set-cookie", ""))
  File "c:\Python27\lib\Cookie.py", line 632, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'
```

**Comment by Hunternif** [comment]
Хм, самоустранилось после перезагрузки
